name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish-linux:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    #if: ${{ github.repository_owner === 'electron-react-boilerplate' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
          
      - name: Install aqtinstall
        run: pip install aqtinstall

      - name: Install Qt6
        run: aqt install-qt linux desktop 6.5.2 gcc_64 --modules qtbase qtmultimedia -O /home/runner/Qt
        
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt install -y cmake
          sudo apt install -y libboost-dev libboost-all-dev
          sudo apt install ninja-build -y
          sudo apt install build-essential -y
          sudo apt install -y cmake python3 perl pkg-config libudev-dev libusb-1.0-0-dev zlib1g-dev
          sudo apt install -y libboost-context-dev
          sudo apt install -y libssl-dev
          sudo apt install -y vulkan-tools
          sudo apt install -y gamemode liblz4-dev
          sudo apt install -y libglib2.0-dev libfuse2 patchelf

      - name: Git clone
        run: |
          cd $HOME
          git clone --recursive https://git.citron-emu.org/Citron/Citron.git

      - name: Build project with CMake
        run: |
          cmake .. -GNinja \
          -DCITRON_USE_BUNDLED_VCPKG=ON \
          -DCITRON_TESTS=OFF \
          -DCITRON_USE_LLVM_DEMANGLE=OFF \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_PREFIX_PATH=/home/runner/Qt/6.7.3/gcc_64
          ninja
          
      - name: Build AppImage
        run: |
          $HOME/Citron/appimage-builder.sh citron $HOME/Citron/build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: citron-AppImage
          path: '**/*.AppImage'
